### ISSUE TITLE
Sorting of Notification Topics

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-kotlin-app#123]
Related to Issue #121, confirm how we are sorting topics when the [NotificationTopics.js](https://data.wsdot.wa.gov/mobile/NotificationTopics.js) file is loaded.

After correcting the spelling, `topic: "manson_county"`, and the topics were refreshed in the app, the `Mason County` title went to the bottom of the list. `Mason County` would only be correctly sorted if the app's data cache was deleted.

If we add new topics in the future, they should appear alphabetical by default.

**Comment by englehorn** [comment]
Issue fixed with this commit: https://github.com/englehorn/wsdot-kotlin-app/commit/30f3f46c93a6273184236ba4b7b31eb24ebd7530#diff-71ada4b5d90d48612308d4e1094c88cfab9ca752d789292a7a7910f614e9cd95
