### ISSUE TITLE
Update bottom sheet view layout

### ISSUE THREAD

**Issue by englehorn** [WSDOT/wsdot-kotlin-app#130]
Bottom sheet view not displaying correctly after updating project dependencies.

**Comment by waynedyck** [comment]
Maybe related, [Starting from version 2.1.0, ConstraintLayout is sporadically laying out children incorrectly](https://github.com/androidx/constraintlayout/issues/421)

**Comment by waynedyck** [comment]
Closed with commit 7de9e565441bc9e77e6c0960bf9c75b2963b9643
