### ISSUE TITLE
Fix traffic map refresh button

### ISSUE THREAD

**Issue by englehorn** [WSDOT/wsdot-kotlin-app#180]
We received feedback from a user that the traffic map refresh button is not working. 

I did some testing and found that the highway alert cache time for the refresh button is set to [one week](https://github.com/WSDOT/wsdot-kotlin-app/blob/9b283df9a22e358ed799e9c221573821c870d150/app/src/main/java/gov/wa/wsdot/android/wsdot/repository/HighwayAlertRepository.kt#L101). 

We should change this cache time to five minutes so that the highway alerts can be refreshed at the same time interval as the mobile data file http://data.wsdot.wa.gov/mobile/HighwayAlerts.js

_Originally posted by @englehorn in https://github.com/WSDOT/wsdot-kotlin-app/issues/177#issuecomment-1442565226_

**Comment by waynedyck** [comment]
The alerts should definitely not be caching for a week; that doesn't make any sense. The cameras, yes, because they don't change that much, but definitely not the alerts.
